apiVersion: v1
kind: Service
metadata:
  name: devops-k8s-operator-controller-manager-metrics-service
  namespace: devops-k8s-operator-system
  labels:
    app.kubernetes.io/name: devops-k8s-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: devops-k8s-operator
